# New Confucianism

## Overview

**Time**

17th century to the 21th century AD

**Representative Figures**

Gu Yanwu(顾炎武), Huang Zongxi(黄宗羲), Liang Shuming(梁漱溟), Mou Zongsan(牟宗三)

## Late Qing and Republican periods

The Confucianism in the Qing Dynasty was deeply influenced by politics, especially after the reign of Emperor Qianlong. The court proclaimed its respect for Song Dynasty learning (though it actually referred to Neo-Confucianism, while the study of the mind, known as Xinxue, was considered heterodox during the Qing Dynasty). Scholars in society no longer practiced Daoism like their predecessors in the Song and Ming dynasties; instead, they focused mainly on textual analysis, claiming to revive the tradition of Han Dynasty studies. During the late Qing and Republican periods, warlord conflicts and cultural decline resulted in a slow development of Confucian thought.

## Confucianism and CPC

From the establishment of the People's Republic of China to the end of the Cultural Revolution, this period marked a stage of dormancy for Confucian thought. During this time, research on Neo-Confucianism not only stagnated on the Chinese mainland but also saw little innovation in Hong Kong, Taiwan, and overseas. The stage of recovery and development began after the end of the Cultural Revolution and is still ongoing. During the recovery stage, some works on Neo-Confucianism re-emerged, prompting academia to reflect on and discuss the merits and demerits of Neo-Confucianism. The development stage is characterized by a comprehensive and thorough reevaluation of Confucianism and Neo-Confucianism, drawing on the essence of ancient wisdom to address contemporary challenges.
